Repository Eclipse-Station/Eclipse-Station-13, pull requests merged in 2019-09, with the labels that each got.

#233 PTrack dump code
  code/controllers/subsystems/dispatcher_debug.dm
  code/modules/admin/admin_verbs.dm
  eclipsestation.dme
Labels: Non-base branch, Spitzer's Bane, Work In Progress

#239 Fixes wheelchair speed
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Labels: Priority: High, bugfix

#237 Spelling And Grammar
  code/_helpers/unsorted.dm
  code/_onclick/drag_drop.dm
  code/game/machinery/computer3/computers/atmos_alert.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/transformer.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/micro/mecha_parts_vr.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/circuitboards/computer/camera_monitor.dm
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/items/weapons/material/material_armor.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/busy_space_vr/organizations.dm
  code/modules/client/asset_cache.dm
  code/modules/clothing/under/accessories/medals.dm
  code/modules/crafting/craft.dm
  code/modules/events/money_spam.dm
  code/modules/events/prison_break.dm
  code/modules/events/solar_storm.dm
  code/modules/examine/descriptions/containers.dm
  code/modules/games/cah_white_cards.dm
  code/modules/lighting/__lighting_docs.dm
  code/modules/lore_codex/legal_code_data/sif_law.dm
  code/modules/mob/dead/observer/free_vr.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/new_player/skill.dm
  code/modules/mob/transform_procs.dm
  code/modules/nano/modules/human_appearance.dm
  code/modules/planet/weather.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Readme.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/xenoarcheaology/tools/geosample_scanner.dm
  maps/RandomZLevels/stationCollision.dm
  maps/RandomZLevels/zoo.dmm
  maps/submaps/_readme.dm
  modular_citadel/code/game/objects/items/upgradekit.dm
  modular_citadel/code/game/objects/random/random_cit.dm
  modular_citadel/code/modules/clothing/suits/medieval_armor.dm
  modular_eclipse/code/modules/clothing/under/polychromic_uniforms.dm
Labels: Spelling and Grammer

#242 Fixes RD not being included into job whitelist
  code/game/jobs/job/science.dm
Labels: Priority: High, bug
