Repository Eclipse-Station/Eclipse-Station-13, pull requests merged in 2019-02, with the labels that each got.

#141 fixes the glass shiv so it now embeds on melee attack
  modular_aeiou/code/game/objects/items/weapons/crafted_weapons_aeiou.dm
Labels: bugfix

#130 Adds the 'Antiseptic Saliva' trait
  aeioustation.dme
  modular_aeiou/code/modules/mob/living/carbon/human/species/station/traits/positive.dm
  modular_aeiou/code/modules/vore/lick_wounds.dm
Labels: Feature

#149 making friends with umbrellas and phaseguns
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/planet/sif.dm
Labels: AEIOU edit, bugfix
